### ISSUE TITLE
dataframe_init.sh needs two different versions of python

### ISSUE THREAD

**Issue by finsellwood** [finsellwood/DeepMODE#9]
*import ROOT* requires python2.7, but using vector.arr needs python3
- could split file up into two
- or rebuild root for python3
- have changed source to python2.7 packages but is a temporary fix - pulls an error when we reach the vector manipulation part

**Comment by finsellwood** [comment]
**Error message**
Traceback (most recent call last):
  File "Python_files/dataframeinit.py", line 8, in <module>
    import ROOT
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf6/lib/ROOT.py", line 24, in <module>
    import cppyy
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf6/lib/cppyy.py", line 61, in <module>
    import libPyROOT as _backend
ImportError: dynamic module does not define module export function (PyInit_libPyROOT)

**Comment by finsellwood** [comment]
Mod file doesnt work because

**Comment by adambrzosko** [comment]
Separated and works properly

**Comment by adambrzosko** [comment]
Separated and works properly
